# rag_examples.py
# This file contains ALL the training examples for the AI

RAG_EXAMPLES = {
    'tasks_ar': [
        # === ORIGINAL ARABIC TASK EXAMPLES (100 examples) ===
                
                # Simple Tasks (30 examples)
                {"input": "اعمل مهمة للواجب الساعة 8 مساء بأولوية عالية", "output": {"tasks": [{"title": "الواجب", "description": "إنهاء الواجب المطلوب", "due_date": "2024-01-15", "due_time": "20:00", "duration": "ساعتان", "priority": "high", "category": "study"}]}},
                {"input": "أنشئ مهمة للدراسة غداً", "output": {"tasks": [{"title": "جلسة الدراسة", "description": "التحضير والمراجعة", "due_date": "2024-01-16", "due_time": "14:00", "duration": "3 ساعات", "priority": "high", "category": "study"}]}},
                {"input": "أريد التمرين وطبخ العشاء الليلة", "output": {"tasks": [{"title": "التمارين الرياضية", "description": "ممارسة الرياضة اليومية", "due_date": "2024-01-15", "due_time": "19:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "تحضير العشاء", "description": "طهي وجبة المساء", "due_date": "2024-01-15", "due_time": "20:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "أنشئ مهمة", "output": {"tasks": [{"title": "مهمة جديدة", "description": "وصف المهمة", "due_date": "2024-01-15", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة", "output": {"tasks": [{"title": "مهمة", "description": "مهمة للإنجاز", "due_date": "2024-01-15", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة للواجب الساعة 8 مساء", "output": {"tasks": [{"title": "الواجب", "description": "إنهاء الواجب المطلوب", "due_date": "2024-01-15", "due_time": "20:00", "duration": "ساعتان", "priority": "high", "category": "study"}]}},
                {"input": "أنشئ مهمة للدراسة غداً الساعة 3 عصراً", "output": {"tasks": [{"title": "جلسة الدراسة", "description": "التحضير والمراجعة", "due_date": "2024-01-16", "due_time": "15:00", "duration": "3 ساعات", "priority": "high", "category": "study"}]}},
                {"input": "مهمة للتمارين الساعة 7 مساء", "output": {"tasks": [{"title": "التمارين الرياضية", "description": "ممارسة الرياضة اليومية", "due_date": "2024-01-15", "due_time": "19:00", "duration": "ساعة", "priority": "medium", "category": "health"}]}},
                {"input": "أنشئ مهمة لقراءة كتاب", "output": {"tasks": [{"title": "قراءة الكتاب", "description": "قراءة فصل من الكتاب", "due_date": "2024-01-15", "due_time": "18:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة للتسوق", "output": {"tasks": [{"title": "التسوق", "description": "شراء المستلزمات", "due_date": "2024-01-15", "due_time": "17:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}]}},
                {"input": "مهمة للاجتماع مع أحمد", "output": {"tasks": [{"title": "اجتماع مع أحمد", "description": "مناقشة المشروع", "due_date": "2024-01-15", "due_time": "14:00", "duration": "ساعة", "priority": "high", "category": "work"}]}},
                {"input": "أنشئ مهمة لزيارة الطبيب", "output": {"tasks": [{"title": "زيارة الطبيب", "description": "كشف طبي دوري", "due_date": "2024-01-15", "due_time": "11:00", "duration": "ساعة", "priority": "high", "category": "health"}]}},
                {"input": "مهمة لدفع الفواتير", "output": {"tasks": [{"title": "دفع الفواتير", "description": "تسديد الفواتير المستحقة", "due_date": "2024-01-15", "due_time": "16:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة لتنظيف الغرفة", "output": {"tasks": [{"title": "تنظيف الغرفة", "description": "ترتيب وتنظيف المكان", "due_date": "2024-01-15", "due_time": "10:00", "duration": "ساعة", "priority": "low", "category": "personal"}]}},
                {"input": "مهمة لتحضير العشاء", "output": {"tasks": [{"title": "تحضير العشاء", "description": "طهي وجبة المساء", "due_date": "2024-01-15", "due_time": "19:30", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "أنشئ مهمة للمشروع الجامعي", "output": {"tasks": [{"title": "المشروع الجامعي", "description": "العمل على متطلبات المشروع", "due_date": "2024-01-15", "due_time": "15:00", "duration": "4 ساعات", "priority": "high", "category": "study"}]}},
                {"input": "مهمة لمكالمة العمل", "output": {"tasks": [{"title": "مكالمة عمل", "description": "مناقشة أعمال الشركة", "due_date": "2024-01-15", "due_time": "13:00", "duration": "ساعة", "priority": "high", "category": "work"}]}},
                {"input": "اعمل مهمة لحل الواجب الرياضي", "output": {"tasks": [{"title": "الواجب الرياضي", "description": "حل مسائل الرياضيات", "due_date": "2024-01-15", "due_time": "16:00", "duration": "ساعتان", "priority": "high", "category": "study"}]}},
                {"input": "مهمة لكتابة التقرير", "output": {"tasks": [{"title": "كتابة التقرير", "description": "إعداد التقرير النهائي", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 ساعات", "priority": "medium", "category": "work"}]}},
                {"input": "أنشئ مهمة للمراجعة النهائية", "output": {"tasks": [{"title": "المراجعة النهائية", "description": "مراجعة قبل الامتحان", "due_date": "2024-01-15", "due_time": "09:00", "duration": "ساعتان", "priority": "high", "category": "study"}]}},
                {"input": "مهمة لشراء المستلزمات", "output": {"tasks": [{"title": "شراء المستلزمات", "description": "تسوق للاحتياجات المنزلية", "due_date": "2024-01-15", "due_time": "12:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة للعائلة", "output": {"tasks": [{"title": "وقت العائلة", "description": "التواصل مع أفراد العائلة", "due_date": "2024-01-15", "due_time": "18:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}]}},
                {"input": "مهمة للصلاة", "output": {"tasks": [{"title": "أداء الصلاة", "description": "الصلاة في وقتها", "due_date": "2024-01-15", "due_time": "13:00", "duration": "30 دقيقة", "priority": "high", "category": "personal"}]}},
                {"input": "أنشئ مهمة للراحة", "output": {"tasks": [{"title": "وقت الراحة", "description": "أخذ قسط من الراحة", "due_date": "2024-01-15", "due_time": "16:00", "duration": "30 دقيقة", "priority": "low", "category": "personal"}]}},
                {"input": "مهمة للقراءة اليومية", "output": {"tasks": [{"title": "القراءة اليومية", "description": "قراءة كتاب أو مقال", "due_date": "2024-01-15", "due_time": "21:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة للبرمجة", "output": {"tasks": [{"title": "جلسة البرمجة", "description": "العمل على مشروع برمجي", "due_date": "2024-01-15", "due_time": "10:00", "duration": "3 ساعات", "priority": "high", "category": "work"}]}},
                {"input": "مهمة للاجتماع الافتراضي", "output": {"tasks": [{"title": "اجتماع افتراضي", "description": "اجتماع عبر الإنترنت", "due_date": "2024-01-15", "due_time": "11:00", "duration": "ساعة", "priority": "high", "category": "work"}]}},
                {"input": "أنشئ مهمة للتمارين الصباحية", "output": {"tasks": [{"title": "التمارين الصباحية", "description": "تمارين رياضية في الصباح", "due_date": "2024-01-15", "due_time": "07:00", "duration": "45 دقيقة", "priority": "medium", "category": "health"}]}},
                {"input": "مهمة لتحضير العشاء", "output": {"tasks": [{"title": "تحضير العشاء", "description": "إعداد وجبة العشاء", "due_date": "2024-01-15", "due_time": "18:30", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة للدراسة الجماعية", "output": {"tasks": [{"title": "الدراسة الجماعية", "description": "مذاكرة مع الزملاء", "due_date": "2024-01-15", "due_time": "15:00", "duration": "ساعتان", "priority": "high", "category": "study"}]}},
                {"input": "مهمة لمراجعة البريد الإلكتروني", "output": {"tasks": [{"title": "مراجعة البريد", "description": "الرد على الرسائل الإلكترونية", "due_date": "2024-01-15", "due_time": "09:00", "duration": "ساعة", "priority": "medium", "category": "work"}]}},
                {"input": "أنشئ مهمة للتخطيط للأسبوع", "output": {"tasks": [{"title": "التخطيط الأسبوعي", "description": "تخطيط المهام للأسبوع القادم", "due_date": "2024-01-15", "due_time": "20:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "مهمة لتعلم لغة جديدة", "output": {"tasks": [{"title": "تعلم اللغة", "description": "ممارسة لغة جديدة", "due_date": "2024-01-15", "due_time": "17:00", "duration": "ساعة", "priority": "medium", "category": "study"}]}},
                {"input": "اعمل مهمة للعزف على البيانو", "output": {"tasks": [{"title": "العزف على البيانو", "description": "ممارسة العزف", "due_date": "2024-01-15", "due_time": "19:00", "duration": "ساعة", "priority": "low", "category": "personal"}]}},
                {"input": "مهمة لكتابة المذكرات", "output": {"tasks": [{"title": "كتابة المذكرات", "description": "تدوين الأفكار اليومية", "due_date": "2024-01-15", "due_time": "22:00", "duration": "30 دقيقة", "priority": "low", "category": "personal"}]}},

                # Multiple Tasks (35 examples)
                {"input": "عندي 3 ساعات فراغ من 2 إلى 5، أريد أن أذاكر وأتمرن وآخذ قسطاً من الراحة", "output": {"tasks": [{"title": "المذاكرة", "description": "جلسة دراسة مركزة", "due_date": "2024-01-15", "due_time": "14:00", "duration": "ساعة ونصف", "priority": "high", "category": "study"}, {"title": "التمارين", "description": "نشاط رياضي", "due_date": "2024-01-15", "due_time": "15:30", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "الراحة", "description": "استراحة واسترخاء", "due_date": "2024-01-15", "due_time": "16:30", "duration": "نصف ساعة", "priority": "low", "category": "personal"}]}},
                {"input": "غداً عندي اجتماع صباحي وغداء مع العائلة ودراسة مسائية", "output": {"tasks": [{"title": "الاجتماع الصباحي", "description": "اجتماع العمل", "due_date": "2024-01-16", "due_time": "10:00", "duration": "ساعة", "priority": "high", "category": "work"}, {"title": "غداء العائلة", "description": "تناول الطعام مع العائلة", "due_date": "2024-01-16", "due_time": "13:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}, {"title": "الدراسة المسائية", "description": "مراجعة الدروس", "due_date": "2024-01-16", "due_time": "18:00", "duration": "3 ساعات", "priority": "high", "category": "study"}]}},
                {"input": "أحتاج أن أنظف البيت وأغسل الملابس وأذهب للتسوق", "output": {"tasks": [{"title": "تنظيف البيت", "description": "ترتيب المنزل", "due_date": "2024-01-15", "due_time": "09:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}, {"title": "غسل الملابس", "description": "تنظيف الملابس", "due_date": "2024-01-15", "due_time": "11:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "التسوق", "description": "شراء المستلزمات", "due_date": "2024-01-15", "due_time": "15:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}]}},
                {"input": "اليوم عندي امتحان ثم تمرين ثم قراءة", "output": {"tasks": [{"title": "الامتحان", "description": "اختبار المادة", "due_date": "2024-01-15", "due_time": "10:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "التمرين", "description": "نشاط بدني", "due_date": "2024-01-15", "due_time": "14:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "القراءة", "description": "قراءة كتاب", "due_date": "2024-01-15", "due_time": "17:00", "duration": "ساعة", "priority": "low", "category": "personal"}]}},
                {"input": "أريد أن أخطط ليومي: صلاة الفجر، دراسة، عمل، راحة", "output": {"tasks": [{"title": "صلاة الفجر", "description": "أداء الصلاة", "due_date": "2024-01-15", "due_time": "05:00", "duration": "30 دقيقة", "priority": "high", "category": "personal"}, {"title": "الدراسة", "description": "جلسة مذاكرة", "due_date": "2024-01-15", "due_time": "06:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "العمل", "description": "مهام العمل", "due_date": "2024-01-15", "due_time": "09:00", "duration": "6 ساعات", "priority": "high", "category": "work"}, {"title": "الراحة", "description": "استراحة", "due_date": "2024-01-15", "due_time": "17:00", "duration": "ساعتان", "priority": "low", "category": "personal"}]}},
                {"input": "عندي اجتماعين ومكالمة هاتفية وتقرير أكتبه", "output": {"tasks": [{"title": "الاجتماع الأول", "description": "اجتماع فريق العمل", "due_date": "2024-01-15", "due_time": "10:00", "duration": "ساعة", "priority": "high", "category": "work"}, {"title": "الاجتماع الثاني", "description": "اجتماع مع المدير", "due_date": "2024-01-15", "due_time": "14:00", "duration": "ساعة", "priority": "high", "category": "work"}, {"title": "مكالمة هاتفية", "description": "اتصال مع العميل", "due_date": "2024-01-15", "due_time": "16:00", "duration": "30 دقيقة", "priority": "medium", "category": "work"}, {"title": "كتابة التقرير", "description": "إعداد التقرير النهائي", "due_date": "2024-01-15", "due_time": "17:00", "duration": "ساعتان", "priority": "high", "category": "work"}]}},
                {"input": "أحتاج للذهاب إلى البنك ثم السوبرماركت ثم الصيدلية", "output": {"tasks": [{"title": "البنك", "description": "إنجاز المعاملات البنكية", "due_date": "2024-01-15", "due_time": "10:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "السوبرماركت", "description": "شراء البقالة", "due_date": "2024-01-15", "due_time": "11:30", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "الصيدلية", "description": "شراء الأدوية", "due_date": "2024-01-15", "due_time": "13:00", "duration": "30 دقيقة", "priority": "medium", "category": "personal"}]}},
                {"input": "غداً عندي محاضرة صباحية وتمرين مسائي ومشروع أكمله", "output": {"tasks": [{"title": "المحاضرة الصباحية", "description": "حضور المحاضرة", "due_date": "2024-01-16", "due_time": "09:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "التمرين المسائي", "description": "النشاط الرياضي", "due_date": "2024-01-16", "due_time": "17:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "إكمال المشروع", "description": "العمل على المشروع", "due_date": "2024-01-16", "due_time": "19:00", "duration": "3 ساعات", "priority": "high", "category": "study"}]}},
                {"input": "أريد أن أنظم أسبوعي: دراسة يومياً، تمرين 3 مرات، راحة في نهاية الأسبوع", "output": {"tasks": [{"title": "الدراسة اليومية", "description": "جلسة دراسة يومية", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 ساعات", "priority": "high", "category": "study"}, {"title": "التمرين", "description": "جلسة التمارين", "due_date": "2024-01-15", "due_time": "18:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "التمرين", "description": "جلسة التمارين", "due_date": "2024-01-17", "due_time": "18:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "التمرين", "description": "جلسة التمارين", "due_date": "2024-01-19", "due_time": "18:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "الراحة", "description": "استراحة نهاية الأسبوع", "due_date": "2024-01-20", "due_time": "10:00", "duration": "يوم كامل", "priority": "low", "category": "personal"}]}},
                {"input": "عندي واجبان وامتحان ومشروع هذا الأسبوع", "output": {"tasks": [{"title": "الواجب الأول", "description": "إكمال الواجب الدراسي", "due_date": "2024-01-15", "due_time": "16:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "الواجب الثاني", "description": "إكمال الواجب الدراسي", "due_date": "2024-01-16", "due_time": "16:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "الامتحان", "description": "التحضير للامتحان", "due_date": "2024-01-18", "due_time": "10:00", "duration": "3 ساعات", "priority": "high", "category": "study"}, {"title": "المشروع", "description": "العمل على المشروع", "due_date": "2024-01-19", "due_time": "14:00", "duration": "4 ساعات", "priority": "high", "category": "study"}]}},

                # Day Planning (35 examples)
                {"input": "خطط لي يوم كامل من 8 صباحاً إلى 10 مساء", "output": {"tasks": [{"title": "الفطور والاستعداد", "description": "تحضير لليوم", "due_date": "2024-01-15", "due_time": "08:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "العمل/الدراسة", "description": "جلسة عمل مركزة", "due_date": "2024-01-15", "due_time": "09:00", "duration": "4 ساعات", "priority": "high", "category": "work"}, {"title": "استراحة الغداء", "description": "تناول الطعام", "due_date": "2024-01-15", "due_time": "13:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "جلسة عمل ثانية", "description": "استكمال المهام", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 ساعات", "priority": "high", "category": "work"}, {"title": "التمارين الرياضية", "description": "النشاط البدني", "due_date": "2024-01-15", "due_time": "17:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "وقت العائلة", "description": "التواصل مع الأهل", "due_date": "2024-01-15", "due_time": "19:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}, {"title": "الراحة والقراءة", "description": "استرخاء", "due_date": "2024-01-15", "due_time": "21:00", "duration": "ساعة", "priority": "low", "category": "personal"}]}},
                {"input": "أريد جدولاً لليوم الدراسي من 8 إلى 5", "output": {"tasks": [{"title": "المادة الأولى", "description": "دراسة المادة الصباحية", "due_date": "2024-01-15", "due_time": "08:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "استراحة", "description": "فسحة قصيرة", "due_date": "2024-01-15", "due_time": "10:00", "duration": "30 دقيقة", "priority": "low", "category": "personal"}, {"title": "المادة الثانية", "description": "استكمال الدراسة", "due_date": "2024-01-15", "due_time": "10:30", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "غداء", "description": "تناول الطعام", "due_date": "2024-01-15", "due_time": "12:30", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "مراجعة", "description": "تثبيت المعلومات", "due_date": "2024-01-15", "due_time": "13:30", "duration": "ساعة ونصف", "priority": "high", "category": "study"}, {"title": "حل التمارين", "description": "التطبيق العملي", "due_date": "2024-01-15", "due_time": "15:00", "duration": "ساعتان", "priority": "medium", "category": "study"}]}},
                {"input": "رتب لي يوم عطلة", "output": {"tasks": [{"title": "النوم لوقت متأخر", "description": "الراحة والاسترخاء", "due_date": "2024-01-15", "due_time": "08:00", "duration": "ساعتان", "priority": "low", "category": "personal"}, {"title": "الإفطار", "description": "وجبة الصباح", "due_date": "2024-01-15", "due_time": "10:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "القراءة", "description": "قراءة كتاب ممتع", "due_date": "2024-01-15", "due_time": "11:00", "duration": "ساعتان", "priority": "low", "category": "personal"}, {"title": "النشاط الترفيهي", "description": "مشاهدة فيلم أو نزهة", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 ساعات", "priority": "medium", "category": "personal"}, {"title": "زيارة الأصدقاء", "description": "التواصل الاجتماعي", "due_date": "2024-01-15", "due_time": "17:00", "duration": "3 ساعات", "priority": "medium", "category": "personal"}, {"title": "تحضير الأسبوع", "description": "تخطيط للأيام القادمة", "due_date": "2024-01-15", "due_time": "20:00", "duration": "ساعة", "priority": "high", "category": "personal"}]}},
                {"input": "خطط لي يوم عمل من المنزل", "output": {"tasks": [{"title": "البدء بالعمل", "description": "بدء المهام اليومية", "due_date": "2024-01-15", "due_time": "09:00", "duration": "3 ساعات", "priority": "high", "category": "work"}, {"title": "استراحة قصيرة", "description": "أخذ قسط من الراحة", "due_date": "2024-01-15", "due_time": "12:00", "duration": "30 دقيقة", "priority": "low", "category": "personal"}, {"title": "مكالمات العمل", "description": "الاجتماعات والمكالمات", "due_date": "2024-01-15", "due_time": "12:30", "duration": "ساعة ونصف", "priority": "high", "category": "work"}, {"title": "غداء", "description": "تناول وجبة الغداء", "due_date": "2024-01-15", "due_time": "14:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "إنهاء المهام", "description": "استكمال العمل", "due_date": "2024-01-15", "due_time": "15:00", "duration": "3 ساعات", "priority": "high", "category": "work"}]}},
                {"input": "أنشئ جدولاً ليوم رياضي", "output": {"tasks": [{"title": "الإحماء", "description": "تمارين الإحماء", "due_date": "2024-01-15", "due_time": "07:00", "duration": "30 دقيقة", "priority": "medium", "category": "health"}, {"title": "التمارين القلبية", "description": "تمارين الكارديو", "due_date": "2024-01-15", "due_time": "07:30", "duration": "45 دقيقة", "priority": "high", "category": "health"}, {"title": "تمارين القوة", "description": "رفع الأثقال", "due_date": "2024-01-15", "due_time": "08:15", "duration": "45 دقيقة", "priority": "high", "category": "health"}, {"title": "التمدد", "description": "تمارين المرونة", "due_date": "2024-01-15", "due_time": "09:00", "duration": "30 دقيقة", "priority": "medium", "category": "health"}, {"title": "الراحة والتغذية", "description": "الاسترخاء وتناول الطعام", "due_date": "2024-01-15", "due_time": "09:30", "duration": "ساعة", "priority": "medium", "category": "health"}]}},

                # === ENHANCED ARABIC TASK EXAMPLES (100 NEW examples) ===
                
                # Complex Date and Time Examples (25)
                    # Complex parsing examples - Arabic
                {"input": "أنشئ روتين صباحي: تمارين 7 صباحاً، تأمل 7:30، عمل 8 صباحاً", "output": {"tasks": [{"title": "التمارين", "description": "جلسة التمارين الصباحية", "due_date": "2024-01-15", "due_time": "07:00", "duration": "30 دقيقة", "priority": "medium", "category": "health"}, {"title": "التأمل", "description": "ممارسة التأمل", "due_date": "2024-01-15", "due_time": "07:30", "duration": "30 دقيقة", "priority": "medium", "category": "health"}, {"title": "العمل", "description": "بداية يوم العمل", "due_date": "2024-01-15", "due_time": "08:00", "duration": "4 ساعات", "priority": "high", "category": "work"}]}},
                {"input": "خطط ليومي: دراسة 9-11 صباحاً، غداء 1 ظهراً، عمل على المشروع 2-4 عصراً", "output": {"tasks": [{"title": "جلسة الدراسة", "description": "وقت التعلم المركز", "due_date": "2024-01-15", "due_time": "09:00", "duration": "ساعتان", "priority": "high", "category": "study"}, {"title": "وقت الغداء", "description": "تناول وجبة الغذاء", "due_date": "2024-01-15", "due_time": "13:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "عمل المشروع", "description": "العمل على المشروع الرئيسي", "due_date": "2024-01-15", "due_time": "14:00", "duration": "ساعتان", "priority": "high", "category": "work"}]}},
                {"input": "اعمل مهمة لمشروع البرمجة من 15/نوفمبر/2024 إلى 20/نوفمبر/2024", "output": {"tasks": [{"title": "مشروع البرمجة", "description": "تطوير وتنفيذ مشروع البرمجة", "due_date": "2024-11-15 - 2024-11-20", "start_date": "2024-11-15", "end_date": "2024-11-20", "due_time": "09:00", "duration": "5 أيام", "priority": "high", "category": "work"}]}},
                {"input": "مهمة للعرض التقديمي يوم الثلاثاء 10 صباحاً لمدة ساعتين", "output": {"tasks": [{"title": "العرض التقديمي", "description": "تحضير وتقديم العرض", "due_date": "2024-01-16", "due_time": "10:00", "duration": "ساعتان", "priority": "high", "category": "work"}]}},
                {"input": "خطط لي أسبوع عمل كامل من الإثنين إلى الجمعة", "output": {"tasks": [{"title": "التخطيط الأسبوعي", "description": "تخطيط مهام الأسبوع", "due_date": "2024-01-15 - 2024-01-19", "start_date": "2024-01-15", "end_date": "2024-01-19", "due_time": "08:00", "duration": "5 أيام", "priority": "high", "category": "work"}]}},
                {"input": "مهمة لزيارة العائلة يوم الجمعة 5 عصراً", "output": {"tasks": [{"title": "زيارة العائلة", "description": "زيارة وتواصل مع العائلة", "due_date": "2024-01-19", "due_time": "17:00", "duration": "3 ساعات", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمتين: دورة تعلمية من 10/فبراير ولمدة أسبوع، ومشروع شخصي يبدأ غداً", "output": {"tasks": [{"title": "الدورة التعليمية", "description": "متابعة دورة تعليمية", "due_date": "2024-02-10 - 2024-02-17", "start_date": "2024-02-10", "end_date": "2024-02-17", "due_time": "14:00", "duration": "7 أيام", "priority": "high", "category": "study"}, {"title": "المشروع الشخصي", "description": "بدء العمل على المشروع الشخصي", "due_date": "2024-01-16", "due_time": "10:00", "duration": "2 أسابيع", "priority": "medium", "category": "personal"}]}},
                {"input": "مهمة لحضور مؤتمر من 5 إلى 7 مارس 2024", "output": {"tasks": [{"title": "حضور المؤتمر", "description": "المشاركة في المؤتمر السنوي", "due_date": "2024-03-05 - 2024-03-07", "start_date": "2024-03-05", "end_date": "2024-03-07", "due_time": "09:00", "duration": "3 أيام", "priority": "high", "category": "work"}]}},
                {"input": "أنشئ مهمة للعطلة الصيفية من 1 يوليو إلى 15 يوليو", "output": {"tasks": [{"title": "العطلة الصيفية", "description": "فترة الراحة والاستجمام", "due_date": "2024-07-01 - 2024-07-15", "start_date": "2024-07-01", "end_date": "2024-07-15", "due_time": "00:00", "duration": "15 يوم", "priority": "low", "category": "personal"}]}},
                {"input": "مهمة للتسوق لرمضان من 20 فبراير إلى 10 مارس", "output": {"tasks": [{"title": "تسوق رمضان", "description": "شراء مستلزمات شهر رمضان", "due_date": "2024-02-20 - 2024-03-10", "start_date": "2024-02-20", "end_date": "2024-03-10", "due_time": "14:00", "duration": "19 يوم", "priority": "medium", "category": "personal"}]}},
                {"input": "اعمل مهمة للتدريب الصباحي من 6 إلى 7 صباحاً كل يوم", "output": {"tasks": [{"title": "التدريب الصباحي", "description": "جلسة تدريب يومية", "due_date": "2024-01-15", "due_time": "06:00", "duration": "ساعة", "priority": "medium", "category": "health"}]}},
                {"input": "مهمة لمراجعة الميزانية الشهرية كل أول خميس من الشهر", "output": {"tasks": [{"title": "مراجعة الميزانية", "description": "تحليل المصروفات والدخل", "due_date": "2024-02-01", "due_time": "19:00", "duration": "ساعتان", "priority": "high", "category": "personal"}]}},

                # Complex Project Planning (25)
                {"input": "مشروع تطوير تطبيق جوال بثلاث مراحل: التصميم أسبوع، البرمجة أسبوعين، الاختبار 3 أيام", "output": {"tasks": [{"title": "مرحلة التصميم", "description": "تصميم واجهات التطبيق", "due_date": "2024-01-15 - 2024-01-22", "start_date": "2024-01-15", "end_date": "2024-01-22", "due_time": "09:00", "duration": "7 أيام", "priority": "high", "category": "work"}, {"title": "مرحلة البرمجة", "description": "برمجة التطبيق وتطويره", "due_date": "2024-01-22 - 2024-02-05", "start_date": "2024-01-22", "end_date": "2024-02-05", "due_time": "09:00", "duration": "14 يوم", "priority": "high", "category": "work"}, {"title": "مرحلة الاختبار", "description": "اختبار التطبيق وإصلاح الأخطاء", "due_date": "2024-02-05 - 2024-02-08", "start_date": "2024-02-05", "end_date": "2024-02-08", "due_time": "09:00", "duration": "3 أيام", "priority": "medium", "category": "work"}]}},
                {"input": "خطة بناء منزل: الأساسات 10 أيام، الهيكل 20 يوماً، التشطيب 30 يوماً", "output": {"tasks": [{"title": "مرحلة الأساسات", "description": "حفر وصب الأساسات", "due_date": "2024-03-01 - 2024-03-11", "start_date": "2024-03-01", "end_date": "2024-03-11", "due_time": "07:00", "duration": "10 أيام", "priority": "high", "category": "personal"}, {"title": "مرحلة الهيكل", "description": "بناء الهيكل الإنشائي", "due_date": "2024-03-12 - 2024-04-01", "start_date": "2024-03-12", "end_date": "2024-04-01", "due_time": "07:00", "duration": "20 يوم", "priority": "high", "category": "personal"}, {"title": "مرحلة التشطيب", "description": "أعمال التشطيب النهائية", "due_date": "2024-04-02 - 2024-05-02", "start_date": "2024-04-02", "end_date": "2024-05-02", "due_time": "07:00", "duration": "30 يوم", "priority": "medium", "category": "personal"}]}},
                {"input": "مشروع التخرج: البحث 3 أسابيع، الكتابة أسبوعين، المراجعة أسبوع", "output": {"tasks": [{"title": "مرحلة البحث", "description": "جمع المعلومات والمراجع", "due_date": "2024-04-01 - 2024-04-22", "start_date": "2024-04-01", "end_date": "2024-04-22", "due_time": "10:00", "duration": "21 يوم", "priority": "high", "category": "study"}, {"title": "مرحلة الكتابة", "description": "كتابة محتوى المشروع", "due_date": "2024-04-23 - 2024-05-07", "start_date": "2024-04-23", "end_date": "2024-05-07", "due_time": "10:00", "duration": "14 يوم", "priority": "high", "category": "study"}, {"title": "مرحلة المراجعة", "description": "مراجعة وتصحيح الأخطاء", "due_date": "2024-05-08 - 2024-05-15", "start_date": "2024-05-08", "end_date": "2024-05-15", "due_time": "10:00", "duration": "7 أيام", "priority": "medium", "category": "study"}]}},
                {"input": "تخطيط لحفل الزفاف: حجز القاعة شهرين مسبقاً، الدعوات شهر مسبق، الترتيبات النهائية أسبوع", "output": {"tasks": [{"title": "حجز القاعة", "description": "حجز قاعة الحفل والاستقبال", "due_date": "2024-06-01", "due_time": "10:00", "duration": "يوم", "priority": "high", "category": "personal"}, {"title": "إرسال الدعوات", "description": "طباعة وإرسال دعوات الحفل", "due_date": "2024-07-01", "due_time": "10:00", "duration": "يوم", "priority": "medium", "category": "personal"}, {"title": "الترتيبات النهائية", "description": "التأكد من جميع التفاصيل", "due_date": "2024-07-25 - 2024-08-01", "start_date": "2024-07-25", "end_date": "2024-08-01", "due_time": "10:00", "duration": "7 أيام", "priority": "high", "category": "personal"}]}},
                {"input": "مشروع تطوير موقع إلكتروني: التصميم 5 أيام، البرمجة 10 أيام، النشر 2 يوم", "output": {"tasks": [{"title": "تصميم الموقع", "description": "تصميم واجهات المستخدم", "due_date": "2024-02-01 - 2024-02-06", "start_date": "2024-02-01", "end_date": "2024-02-06", "due_time": "09:00", "duration": "5 أيام", "priority": "high", "category": "work"}, {"title": "برمجة الموقع", "description": "تطوير الوظائف والخواص", "due_date": "2024-02-07 - 2024-02-17", "start_date": "2024-02-07", "end_date": "2024-02-17", "due_time": "09:00", "duration": "10 أيام", "priority": "high", "category": "work"}, {"title": "نشر الموقع", "description": "رفع الموقع على السيرفر", "due_date": "2024-02-18 - 2024-02-20", "start_date": "2024-02-18", "end_date": "2024-02-20", "due_time": "09:00", "duration": "2 يوم", "priority": "medium", "category": "work"}]}},

                # Time-Specific Complex Tasks (25)
                {"input": "اجتماع فريق العمل كل يوم اثنين وأربعاء الساعة 11 صباحاً لمدة ساعة", "output": {"tasks": [{"title": "اجتماع فريق العمل", "description": "اجتماع تنسيقي لفريق العمل", "due_date": "2024-01-15", "due_time": "11:00", "duration": "ساعة", "priority": "high", "category": "work"}, {"title": "اجتماع فريق العمل", "description": "اجتماع تنسيقي لفريق العمل", "due_date": "2024-01-17", "due_time": "11:00", "duration": "ساعة", "priority": "high", "category": "work"}]}},
                {"input": "دورة اللغة الإنجليزية كل يوم ثلاثاء وخميس من 6 إلى 8 مساءً", "output": {"tasks": [{"title": "دورة الإنجليزية", "description": "حضور حصة اللغة الإنجليزية", "due_date": "2024-01-16", "due_time": "18:00", "duration": "ساعتان", "priority": "medium", "category": "study"}, {"title": "دورة الإنجليزية", "description": "حضور حصة اللغة الإنجليزية", "due_date": "2024-01-18", "due_time": "18:00", "duration": "ساعتان", "priority": "medium", "category": "study"}]}},
                {"input": "تمارين الصباح يومياً من 7 إلى 7:45 صباحاً", "output": {"tasks": [{"title": "تمارين الصباح", "description": "التمارين الرياضية الصباحية", "due_date": "2024-01-15", "due_time": "07:00", "duration": "45 دقيقة", "priority": "medium", "category": "health"}]}},
                {"input": "قراءة القرآن بعد صلاة الفجر لمدة 30 دقيقة", "output": {"tasks": [{"title": "قراءة القرآن", "description": "تلاوة وحفظ القرآن الكريم", "due_date": "2024-01-15", "due_time": "05:30", "duration": "30 دقيقة", "priority": "high", "category": "personal"}]}},
                {"input": "مذاكرة المواد الدراسية من 4 إلى 7 مساءً يومياً ما عدا الجمعة", "output": {"tasks": [{"title": "المذاكرة المسائية", "description": "جلسة الدراسة اليومية", "due_date": "2024-01-15", "due_time": "16:00", "duration": "3 ساعات", "priority": "high", "category": "study"}]}},

                # Advanced Task Combinations (25)
                {"input": "أنشئ روتين صباحي: تمارين 6-7، فطور 7-7:30، قراءة 7:30-8، عمل 8-12", "output": {"tasks": [{"title": "التمارين الصباحية", "description": "جلسة التمارين الرياضية", "due_date": "2024-01-15", "due_time": "06:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "وجبة الفطور", "description": "تناول وجبة الإفطار", "due_date": "2024-01-15", "due_time": "07:00", "duration": "30 دقيقة", "priority": "medium", "category": "personal"}, {"title": "القراءة الصباحية", "description": "قراءة كتاب أو مقال", "due_date": "2024-01-15", "due_time": "07:30", "duration": "30 دقيقة", "priority": "low", "category": "personal"}, {"title": "بدء العمل", "description": "بدء المهام العملية", "due_date": "2024-01-15", "due_time": "08:00", "duration": "4 ساعات", "priority": "high", "category": "work"}]}},
                {"input": "خطط لي أسبوع تنمية شخصية: قراءة كتاب، تعلم مهارة جديدة، ممارسة الرياضة، التأمل", "output": {"tasks": [{"title": "قراءة الكتاب", "description": "إكمال قراءة كتاب التنمية", "due_date": "2024-01-15", "due_time": "20:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "تعلم مهارة جديدة", "description": "ممارسة مهارة التصميم", "due_date": "2024-01-16", "due_time": "19:00", "duration": "ساعة", "priority": "medium", "category": "personal"}, {"title": "التمارين الرياضية", "description": "جلسة رياضية أسبوعية", "due_date": "2024-01-17", "due_time": "18:00", "duration": "ساعة", "priority": "medium", "category": "health"}, {"title": "جلسة التأمل", "description": "ممارسة التأمل والاسترخاء", "due_date": "2024-01-18", "due_time": "07:00", "duration": "30 دقيقة", "priority": "low", "category": "personal"}]}},
                {"input": "مهام السفر: حجز التذاكر، تجهيز الحقائب، تأكيد الحجز، صرف العملة", "output": {"tasks": [{"title": "حجز تذاكر السفر", "description": "حجز تذاكر الطيران", "due_date": "2024-02-01", "due_time": "10:00", "duration": "ساعة", "priority": "high", "category": "personal"}, {"title": "تجهيز الحقائب", "description": "ترتيب ملابس ومستلزمات السفر", "due_date": "2024-02-14", "due_time": "18:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}, {"title": "تأكيد الحجز", "description": "التأكد من حجز الفندق", "due_date": "2024-02-15", "due_time": "11:00", "duration": "30 دقيقة", "priority": "medium", "category": "personal"}, {"title": "صرف العملة", "description": "تحويل العملة للعملة المحلية", "due_date": "2024-02-16", "due_time": "14:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "تحضير لحفل عيد الميلاد: شراء الهدايا، تزيين المكان، تحضير الطعام، دعوة الأصدقاء", "output": {"tasks": [{"title": "شراء الهدايا", "description": "شراء هدايا للحفل", "due_date": "2024-03-20", "due_time": "15:00", "duration": "ساعتان", "priority": "medium", "category": "personal"}, {"title": "تزيين المكان", "description": "ترتيب وتزيين قاعة الحفل", "due_date": "2024-03-24", "due_time": "10:00", "duration": "3 ساعات", "priority": "medium", "category": "personal"}, {"title": "تحضير الطعام", "description": "إعداد وجبات الحفل", "due_date": "2024-03-24", "due_time": "14:00", "duration": "4 ساعات", "priority": "high", "category": "personal"}, {"title": "دعوة الأصدقاء", "description": "إرسال دعوات الحضور", "due_date": "2024-03-18", "due_time": "12:00", "duration": "ساعة", "priority": "medium", "category": "personal"}]}},
                {"input": "مشروع تجديد المنزل: دهان الغرف، تركيب أرضيات، تجديد الأثاث، تنظيف نهائي", "output": {"tasks": [{"title": "دهان الغرف", "description": "طلاء جدران المنزل", "due_date": "2024-04-01 - 2024-04-03", "start_date": "2024-04-01", "end_date": "2024-04-03", "due_time": "08:00", "duration": "3 أيام", "priority": "high", "category": "personal"}, {"title": "تركيب الأرضيات", "description": "تركيب الأرضيات الجديدة", "due_date": "2024-04-04 - 2024-04-06", "start_date": "2024-04-04", "end_date": "2024-04-06", "due_time": "08:00", "duration": "3 أيام", "priority": "high", "category": "personal"}, {"title": "تجديد الأثاث", "description": "ترميم وتجديد قطع الأثاث", "due_date": "2024-04-07 - 2024-04-10", "start_date": "2024-04-07", "end_date": "2024-04-10", "due_time": "09:00", "duration": "4 أيام", "priority": "medium", "category": "personal"}, {"title": "التنظيف النهائي", "description": "تنظيف المنزل بعد التجديد", "due_date": "2024-04-11", "due_time": "08:00", "duration": "يوم", "priority": "medium", "category": "personal"}]}},
        
    ],
    
    'tasks_en': [
        # === ORIGINAL ENGLISH TASK EXAMPLES (100 examples) ===
                
                # Simple Tasks (30 examples)
                {"input": "Create task for homework at 8pm with high priority", "output": {"tasks": [{"title": "Homework", "description": "Complete homework assignment", "due_date": "2024-01-15", "due_time": "20:00", "duration": "2 hours", "priority": "high", "category": "study"}]}},
                {"input": "Make a task for studying tomorrow", "output": {"tasks": [{"title": "Study Session", "description": "Prepare and review materials", "due_date": "2024-01-16", "due_time": "14:00", "duration": "3 hours", "priority": "high", "category": "study"}]}},
                {"input": "I need to exercise and cook dinner tonight", "output": {"tasks": [{"title": "Exercise", "description": "Daily workout session", "due_date": "2024-01-15", "due_time": "19:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Cook Dinner", "description": "Prepare evening meal", "due_date": "2024-01-15", "due_time": "20:00", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Create a task", "output": {"tasks": [{"title": "New Task", "description": "Task description", "due_date": "2024-01-15", "priority": "medium", "category": "personal"}]}},
                {"input": "Make task", "output": {"tasks": [{"title": "Task", "description": "Task to complete", "due_date": "2024-01-15", "priority": "medium", "category": "personal"}]}},
                {"input": "Create task for homework at 8pm", "output": {"tasks": [{"title": "Homework", "description": "Complete homework assignment", "due_date": "2024-01-15", "due_time": "20:00", "duration": "2 hours", "priority": "high", "category": "study"}]}},
                {"input": "Make a task for studying tomorrow at 3pm", "output": {"tasks": [{"title": "Study Session", "description": "Prepare and review materials", "due_date": "2024-01-16", "due_time": "15:00", "duration": "3 hours", "priority": "high", "category": "study"}]}},
                {"input": "Task for exercise at 7pm", "output": {"tasks": [{"title": "Exercise", "description": "Daily workout session", "due_date": "2024-01-15", "due_time": "19:00", "duration": "1 hour", "priority": "medium", "category": "health"}]}},
                {"input": "Create task for reading book", "output": {"tasks": [{"title": "Read Book", "description": "Read a chapter", "due_date": "2024-01-15", "due_time": "18:00", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Make task for shopping", "output": {"tasks": [{"title": "Shopping", "description": "Buy groceries and supplies", "due_date": "2024-01-15", "due_time": "17:00", "duration": "2 hours", "priority": "medium", "category": "personal"}]}},
                {"input": "Task for meeting with John", "output": {"tasks": [{"title": "Meeting with John", "description": "Discuss project details", "due_date": "2024-01-15", "due_time": "14:00", "duration": "1 hour", "priority": "high", "category": "work"}]}},
                {"input": "Create task for doctor appointment", "output": {"tasks": [{"title": "Doctor Appointment", "description": "Regular medical checkup", "due_date": "2024-01-15", "due_time": "11:00", "duration": "1 hour", "priority": "high", "category": "health"}]}},
                {"input": "Task for paying bills", "output": {"tasks": [{"title": "Pay Bills", "description": "Settle due payments", "due_date": "2024-01-15", "due_time": "16:00", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Make task for cleaning room", "output": {"tasks": [{"title": "Clean Room", "description": "Organize and tidy space", "due_date": "2024-01-15", "due_time": "10:00", "duration": "1 hour", "priority": "low", "category": "personal"}]}},
                {"input": "Task for cooking dinner", "output": {"tasks": [{"title": "Cook Dinner", "description": "Prepare evening meal", "due_date": "2024-01-15", "due_time": "19:30", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Create task for university project", "output": {"tasks": [{"title": "University Project", "description": "Work on project requirements", "due_date": "2024-01-15", "due_time": "15:00", "duration": "4 hours", "priority": "high", "category": "study"}]}},
                {"input": "Task for work call", "output": {"tasks": [{"title": "Work Call", "description": "Discuss company matters", "due_date": "2024-01-15", "due_time": "13:00", "duration": "1 hour", "priority": "high", "category": "work"}]}},
                {"input": "Make task for math homework", "output": {"tasks": [{"title": "Math Homework", "description": "Solve math problems", "due_date": "2024-01-15", "due_time": "16:00", "duration": "2 hours", "priority": "high", "category": "study"}]}},
                {"input": "Task for writing report", "output": {"tasks": [{"title": "Write Report", "description": "Prepare final report", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 hours", "priority": "medium", "category": "work"}]}},
                {"input": "Create task for final review", "output": {"tasks": [{"title": "Final Review", "description": "Review before exam", "due_date": "2024-01-15", "due_time": "09:00", "duration": "2 hours", "priority": "high", "category": "study"}]}},
                {"input": "Task for buying supplies", "output": {"tasks": [{"title": "Buy Supplies", "description": "Shop for household needs", "due_date": "2024-01-15", "due_time": "12:00", "duration": "2 hours", "priority": "medium", "category": "personal"}]}},
                {"input": "Make task for family time", "output": {"tasks": [{"title": "Family Time", "description": "Connect with family members", "due_date": "2024-01-15", "due_time": "18:00", "duration": "2 hours", "priority": "medium", "category": "personal"}]}},
                {"input": "Task for prayer", "output": {"tasks": [{"title": "Prayer", "description": "Perform prayer on time", "due_date": "2024-01-15", "due_time": "13:00", "duration": "30 minutes", "priority": "high", "category": "personal"}]}},
                {"input": "Create task for rest", "output": {"tasks": [{"title": "Rest Time", "description": "Take a break", "due_date": "2024-01-15", "due_time": "16:00", "duration": "30 minutes", "priority": "low", "category": "personal"}]}},
                {"input": "Task for daily reading", "output": {"tasks": [{"title": "Daily Reading", "description": "Read book or article", "due_date": "2024-01-15", "due_time": "21:00", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Make task for programming", "output": {"tasks": [{"title": "Programming Session", "description": "Work on coding project", "due_date": "2024-01-15", "due_time": "10:00", "duration": "3 hours", "priority": "high", "category": "work"}]}},
                {"input": "Task for virtual meeting", "output": {"tasks": [{"title": "Virtual Meeting", "description": "Online meeting", "due_date": "2024-01-15", "due_time": "11:00", "duration": "1 hour", "priority": "high", "category": "work"}]}},
                {"input": "Create task for morning exercise", "output": {"tasks": [{"title": "Morning Exercise", "description": "Morning workout routine", "due_date": "2024-01-15", "due_time": "07:00", "duration": "45 minutes", "priority": "medium", "category": "health"}]}},
                {"input": "Task for preparing dinner", "output": {"tasks": [{"title": "Prepare Dinner", "description": "Cook evening meal", "due_date": "2024-01-15", "due_time": "18:30", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Make task for group study", "output": {"tasks": [{"title": "Group Study", "description": "Study with classmates", "due_date": "2024-01-15", "due_time": "15:00", "duration": "2 hours", "priority": "high", "category": "study"}]}},
                {"input": "Task for checking email", "output": {"tasks": [{"title": "Check Email", "description": "Respond to emails", "due_date": "2024-01-15", "due_time": "09:00", "duration": "1 hour", "priority": "medium", "category": "work"}]}},
                {"input": "Create task for weekly planning", "output": {"tasks": [{"title": "Weekly Planning", "description": "Plan tasks for next week", "due_date": "2024-01-15", "due_time": "20:00", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Task for learning new language", "output": {"tasks": [{"title": "Learn Language", "description": "Practice new language", "due_date": "2024-01-15", "due_time": "17:00", "duration": "1 hour", "priority": "medium", "category": "study"}]}},
                {"input": "Make task for piano practice", "output": {"tasks": [{"title": "Piano Practice", "description": "Practice playing piano", "due_date": "2024-01-15", "due_time": "19:00", "duration": "1 hour", "priority": "low", "category": "personal"}]}},
                {"input": "Task for journal writing", "output": {"tasks": [{"title": "Journal Writing", "description": "Write daily thoughts", "due_date": "2024-01-15", "due_time": "22:00", "duration": "30 minutes", "priority": "low", "category": "personal"}]}},

                # Multiple Tasks (35 examples)
                {"input": "I have 3 free hours from 2 to 5pm, I want to study, exercise and take a break", "output": {"tasks": [{"title": "Study", "description": "Focused study session", "due_date": "2024-01-15", "due_time": "14:00", "duration": "1.5 hours", "priority": "high", "category": "study"}, {"title": "Exercise", "description": "Physical activity", "due_date": "2024-01-15", "due_time": "15:30", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Break", "description": "Rest and relaxation", "due_date": "2024-01-15", "due_time": "16:30", "duration": "30 minutes", "priority": "low", "category": "personal"}]}},
                {"input": "Tomorrow I have morning meeting, lunch with family, and evening study", "output": {"tasks": [{"title": "Morning Meeting", "description": "Work meeting", "due_date": "2024-01-16", "due_time": "10:00", "duration": "1 hour", "priority": "high", "category": "work"}, {"title": "Family Lunch", "description": "Meal with family", "due_date": "2024-01-16", "due_time": "13:00", "duration": "2 hours", "priority": "medium", "category": "personal"}, {"title": "Evening Study", "description": "Review lessons", "due_date": "2024-01-16", "due_time": "18:00", "duration": "3 hours", "priority": "high", "category": "study"}]}},
                {"input": "I need to clean house, do laundry, and go shopping", "output": {"tasks": [{"title": "Clean House", "description": "Tidy up home", "due_date": "2024-01-15", "due_time": "09:00", "duration": "2 hours", "priority": "medium", "category": "personal"}, {"title": "Do Laundry", "description": "Wash clothes", "due_date": "2024-01-15", "due_time": "11:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Go Shopping", "description": "Buy supplies", "due_date": "2024-01-15", "due_time": "15:00", "duration": "2 hours", "priority": "medium", "category": "personal"}]}},
                {"input": "Today I have exam, then exercise, then reading", "output": {"tasks": [{"title": "Exam", "description": "Subject test", "due_date": "2024-01-15", "due_time": "10:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Exercise", "description": "Physical workout", "due_date": "2024-01-15", "due_time": "14:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Reading", "description": "Book reading", "due_date": "2024-01-15", "due_time": "17:00", "duration": "1 hour", "priority": "low", "category": "personal"}]}},
                {"input": "I want to plan my day: morning prayer, study, work, rest", "output": {"tasks": [{"title": "Morning Prayer", "description": "Perform prayer", "due_date": "2024-01-15", "due_time": "05:00", "duration": "30 minutes", "priority": "high", "category": "personal"}, {"title": "Study", "description": "Study session", "due_date": "2024-01-15", "due_time": "06:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Work", "description": "Work tasks", "due_date": "2024-01-15", "due_time": "09:00", "duration": "6 hours", "priority": "high", "category": "work"}, {"title": "Rest", "description": "Break time", "due_date": "2024-01-15", "due_time": "17:00", "duration": "2 hours", "priority": "low", "category": "personal"}]}},
                {"input": "I have two meetings and a phone call and a report to write", "output": {"tasks": [{"title": "First Meeting", "description": "Team work meeting", "due_date": "2024-01-15", "due_time": "10:00", "duration": "1 hour", "priority": "high", "category": "work"}, {"title": "Second Meeting", "description": "Meeting with manager", "due_date": "2024-01-15", "due_time": "14:00", "duration": "1 hour", "priority": "high", "category": "work"}, {"title": "Phone Call", "description": "Call with client", "due_date": "2024-01-15", "due_time": "16:00", "duration": "30 minutes", "priority": "medium", "category": "work"}, {"title": "Write Report", "description": "Prepare final report", "due_date": "2024-01-15", "due_time": "17:00", "duration": "2 hours", "priority": "high", "category": "work"}]}},
                {"input": "I need to go to bank, then supermarket, then pharmacy", "output": {"tasks": [{"title": "Bank", "description": "Handle banking matters", "due_date": "2024-01-15", "due_time": "10:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Supermarket", "description": "Buy groceries", "due_date": "2024-01-15", "due_time": "11:30", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Pharmacy", "description": "Buy medicines", "due_date": "2024-01-15", "due_time": "13:00", "duration": "30 minutes", "priority": "medium", "category": "personal"}]}},
                {"input": "Tomorrow I have morning lecture, evening exercise, and project to complete", "output": {"tasks": [{"title": "Morning Lecture", "description": "Attend lecture", "due_date": "2024-01-16", "due_time": "09:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Evening Exercise", "description": "Physical activity", "due_date": "2024-01-16", "due_time": "17:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Complete Project", "description": "Work on project", "due_date": "2024-01-16", "due_time": "19:00", "duration": "3 hours", "priority": "high", "category": "study"}]}},
                {"input": "I want to organize my week: daily study, exercise 3 times, rest on weekend", "output": {"tasks": [{"title": "Daily Study", "description": "Daily study session", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 hours", "priority": "high", "category": "study"}, {"title": "Exercise", "description": "Workout session", "due_date": "2024-01-15", "due_time": "18:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Exercise", "description": "Workout session", "due_date": "2024-01-17", "due_time": "18:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Exercise", "description": "Workout session", "due_date": "2024-01-19", "due_time": "18:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Rest", "description": "Weekend break", "due_date": "2024-01-20", "due_time": "10:00", "duration": "full day", "priority": "low", "category": "personal"}]}},
                {"input": "I have two homeworks and an exam and a project this week", "output": {"tasks": [{"title": "First Homework", "description": "Complete school homework", "due_date": "2024-01-15", "due_time": "16:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Second Homework", "description": "Complete school homework", "due_date": "2024-01-16", "due_time": "16:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Exam", "description": "Prepare for exam", "due_date": "2024-01-18", "due_time": "10:00", "duration": "3 hours", "priority": "high", "category": "study"}, {"title": "Project", "description": "Work on project", "due_date": "2024-01-19", "due_time": "14:00", "duration": "4 hours", "priority": "high", "category": "study"}]}},

                # Day Planning (35 examples)
                {"input": "Plan my full day from 8am to 10pm", "output": {"tasks": [{"title": "Breakfast & Prep", "description": "Get ready for day", "due_date": "2024-01-15", "due_time": "08:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Work/Study", "description": "Focused work session", "due_date": "2024-01-15", "due_time": "09:00", "duration": "4 hours", "priority": "high", "category": "work"}, {"title": "Lunch Break", "description": "Meal time", "due_date": "2024-01-15", "due_time": "13:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Second Work Session", "description": "Continue tasks", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 hours", "priority": "high", "category": "work"}, {"title": "Exercise", "description": "Physical activity", "due_date": "2024-01-15", "due_time": "17:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Family Time", "description": "Connect with family", "due_date": "2024-01-15", "due_time": "19:00", "duration": "2 hours", "priority": "medium", "category": "personal"}, {"title": "Relax & Read", "description": "Wind down", "due_date": "2024-01-15", "due_time": "21:00", "duration": "1 hour", "priority": "low", "category": "personal"}]}},
                {"input": "I need schedule for study day from 8 to 5", "output": {"tasks": [{"title": "First Subject", "description": "Morning study session", "due_date": "2024-01-15", "due_time": "08:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Short Break", "description": "Quick rest", "due_date": "2024-01-15", "due_time": "10:00", "duration": "30 minutes", "priority": "low", "category": "personal"}, {"title": "Second Subject", "description": "Continue studying", "due_date": "2024-01-15", "due_time": "10:30", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Lunch", "description": "Meal break", "due_date": "2024-01-15", "due_time": "12:30", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Review", "description": "Reinforce learning", "due_date": "2024-01-15", "due_time": "13:30", "duration": "1.5 hours", "priority": "high", "category": "study"}, {"title": "Practice", "description": "Apply knowledge", "due_date": "2024-01-15", "due_time": "15:00", "duration": "2 hours", "priority": "medium", "category": "study"}]}},
                {"input": "Plan my weekend day", "output": {"tasks": [{"title": "Sleep In", "description": "Rest and relax", "due_date": "2024-01-15", "due_time": "08:00", "duration": "2 hours", "priority": "low", "category": "personal"}, {"title": "Breakfast", "description": "Morning meal", "due_date": "2024-01-15", "due_time": "10:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Reading", "description": "Enjoyable book reading", "due_date": "2024-01-15", "due_time": "11:00", "duration": "2 hours", "priority": "low", "category": "personal"}, {"title": "Leisure Activity", "description": "Movie or outing", "due_date": "2024-01-15", "due_time": "14:00", "duration": "3 hours", "priority": "medium", "category": "personal"}, {"title": "Friends Visit", "description": "Social time", "due_date": "2024-01-15", "due_time": "17:00", "duration": "3 hours", "priority": "medium", "category": "personal"}, {"title": "Week Preparation", "description": "Plan upcoming week", "due_date": "2024-01-15", "due_time": "20:00", "duration": "1 hour", "priority": "high", "category": "personal"}]}},
                {"input": "Plan my work from home day", "output": {"tasks": [{"title": "Start Work", "description": "Begin daily tasks", "due_date": "2024-01-15", "due_time": "09:00", "duration": "3 hours", "priority": "high", "category": "work"}, {"title": "Short Break", "description": "Take a rest", "due_date": "2024-01-15", "due_time": "12:00", "duration": "30 minutes", "priority": "low", "category": "personal"}, {"title": "Work Calls", "description": "Meetings and calls", "due_date": "2024-01-15", "due_time": "12:30", "duration": "1.5 hours", "priority": "high", "category": "work"}, {"title": "Lunch", "description": "Have lunch", "due_date": "2024-01-15", "due_time": "14:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Finish Tasks", "description": "Complete work", "due_date": "2024-01-15", "due_time": "15:00", "duration": "3 hours", "priority": "high", "category": "work"}]}},
                {"input": "Create schedule for sports day", "output": {"tasks": [{"title": "Warm Up", "description": "Warm up exercises", "due_date": "2024-01-15", "due_time": "07:00", "duration": "30 minutes", "priority": "medium", "category": "health"}, {"title": "Cardio Exercises", "description": "Cardio workout", "due_date": "2024-01-15", "due_time": "07:30", "duration": "45 minutes", "priority": "high", "category": "health"}, {"title": "Strength Training", "description": "Weight lifting", "due_date": "2024-01-15", "due_time": "08:15", "duration": "45 minutes", "priority": "high", "category": "health"}, {"title": "Stretching", "description": "Flexibility exercises", "due_date": "2024-01-15", "due_time": "09:00", "duration": "30 minutes", "priority": "medium", "category": "health"}, {"title": "Rest & Nutrition", "description": "Relax and eat", "due_date": "2024-01-15", "due_time": "09:30", "duration": "1 hour", "priority": "medium", "category": "health"}]}},

                # === ENHANCED ENGLISH TASK EXAMPLES (100 NEW examples) ===
                
                # Complex Date and Time Examples (25)
                {"input": "Create morning routine: exercise 7am, meditation 7:30, work 8am", "output": {"tasks": [{"title": "Exercise", "description": "Morning workout session", "due_date": "2024-01-15", "due_time": "07:00", "duration": "30 minutes", "priority": "medium", "category": "health"}, {"title": "Meditation", "description": "Mindfulness practice", "due_date": "2024-01-15", "due_time": "07:30", "duration": "30 minutes", "priority": "medium", "category": "health"}, {"title": "Work", "description": "Start work day", "due_date": "2024-01-15", "due_time": "08:00", "duration": "4 hours", "priority": "high", "category": "work"}]}},
                {"input": "Plan my day: study 9-11am, lunch 1pm, project work 2-4pm", "output": {"tasks": [{"title": "Study Session", "description": "Focused learning time", "due_date": "2024-01-15", "due_time": "09:00", "duration": "2 hours", "priority": "high", "category": "study"}, {"title": "Lunch Break", "description": "Meal time", "due_date": "2024-01-15", "due_time": "13:00", "duration": "1 hour", "priority": "medium", "category": "personal"}, {"title": "Project Work", "description": "Work on main project", "due_date": "2024-01-15", "due_time": "14:00", "duration": "2 hours", "priority": "high", "category": "work"}]}},
                {"input": "Schedule: team meeting 10am (1 hour), client call 2pm (30 min), report writing 3pm", "output": {"tasks": [{"title": "Team Meeting", "description": "Weekly team coordination", "due_date": "2024-01-15", "due_time": "10:00", "duration": "1 hour", "priority": "high", "category": "work"}, {"title": "Client Call", "description": "Discussion with client", "due_date": "2024-01-15", "due_time": "14:00", "duration": "30 minutes", "priority": "high", "category": "work"}, {"title": "Report Writing", "description": "Prepare project report", "due_date": "2024-01-15", "due_time": "15:00", "duration": "2 hours", "priority": "medium", "category": "work"}]}},
                {"input": "Create a project task from 15/November/2024 to 20/November/2024", "output": {"tasks": [{"title": "Project Development", "description": "Work on the main project", "due_date": "2024-11-15 - 2024-11-20", "start_date": "2024-11-15", "end_date": "2024-11-20", "due_time": "09:00", "duration": "5 days", "priority": "high", "category": "work"}]}},
                {"input": "Task for presentation on Tuesday at 10am for 2 hours", "output": {"tasks": [{"title": "Presentation", "description": "Prepare and deliver presentation", "due_date": "2024-01-16", "due_time": "10:00", "duration": "2 hours", "priority": "high", "category": "work"}]}},
                {"input": "Plan my full work week from Monday to Friday", "output": {"tasks": [{"title": "Weekly Planning", "description": "Plan weekly tasks and schedule", "due_date": "2024-01-15 - 2024-01-19", "start_date": "2024-01-15", "end_date": "2024-01-19", "due_time": "08:00", "duration": "5 days", "priority": "high", "category": "work"}]}},
                {"input": "Create tasks for my morning routine: exercise 7-8am, meditation 8-8:30am, work 9am-12pm", "output": {"tasks": [{"title": "Morning Exercise", "description": "Daily workout routine", "due_date": "2024-01-15", "due_time": "07:00", "duration": "1 hour", "priority": "medium", "category": "health"}, {"title": "Meditation", "description": "Mindfulness practice", "due_date": "2024-01-15", "due_time": "08:00", "duration": "30 minutes", "priority": "medium", "category": "personal"}, {"title": "Work Session", "description": "Focused work time", "due_date": "2024-01-15", "due_time": "09:00", "duration": "3 hours", "priority": "high", "category": "work"}]}},
                {"input": "Task for conference attendance from 5th to 7th March 2024", "output": {"tasks": [{"title": "Conference Attendance", "description": "Participate in annual conference", "due_date": "2024-03-05 - 2024-03-07", "start_date": "2024-03-05", "end_date": "2024-03-07", "due_time": "09:00", "duration": "3 days", "priority": "high", "category": "work"}]}},
                {"input": "Create task for summer vacation from July 1st to July 15th", "output": {"tasks": [{"title": "Summer Vacation", "description": "Rest and relaxation period", "due_date": "2024-07-01 - 2024-07-15", "start_date": "2024-07-01", "end_date": "2024-07-15", "due_time": "00:00", "duration": "15 days", "priority": "low", "category": "personal"}]}},
                {"input": "Task for Ramadan shopping from February 20th to March 10th", "output": {"tasks": [{"title": "Ramadan Shopping", "description": "Buy supplies for Ramadan", "due_date": "2024-02-20 - 2024-03-10", "start_date": "2024-02-20", "end_date": "2024-03-10", "due_time": "14:00", "duration": "19 days", "priority": "medium", "category": "personal"}]}},
                {"input": "Create task for morning training from 6 to 7am every day", "output": {"tasks": [{"title": "Morning Training", "description": "Daily training session", "due_date": "2024-01-15", "due_time": "06:00", "duration": "1 hour", "priority": "medium", "category": "health"}]}},
                {"input": "Task for monthly budget review every first Thursday of the month", "output": {"tasks": [{"title": "Monthly Budget Review", "description": "Analyze expenses and income", "due_date": "2024-02-01", "due_time": "19:00", "duration": "2 hours", "priority": "high", "category": "personal"}]}},

                # Complex Project Planning (25)
                {"input": "Mobile app development project with three phases: design 1 week, coding 2 weeks, testing 3 days", "output": {"tasks": [{"title": "Design Phase", "description": "Create app design and wireframes", "due_date": "2024-01-15 - 2024-01-22", "start_date": "2024-01-15", "end_date": "2024-01-22", "due_time": "09:00", "duration": "7 days", "priority": "high", "category": "work"}, {"title": "Coding Phase", "description": "Develop and code the application", "due_date": "2024-01-22 - 2024-02-05", "start_date": "2024-01-22", "end_date": "2024-02-05", "due_time": "09:00", "duration": "14 days", "priority": "high", "category": "work"}, {"title": "Testing Phase", "description": "Test and debug the application", "due_date": "2024-02-05 - 2024-02-08", "start_date": "2024-02-05", "end_date": "2024-02-08", "due_time": "09:00", "duration": "3 days", "priority": "medium", "category": "work"}]}},
                {"input": "House construction plan: foundations 10 days, structure 20 days, finishing 30 days", "output": {"tasks": [{"title": "Foundations Phase", "description": "Dig and pour foundations", "due_date": "2024-03-01 - 2024-03-11", "start_date": "2024-03-01", "end_date": "2024-03-11", "due_time": "07:00", "duration": "10 days", "priority": "high", "category": "personal"}, {"title": "Structure Phase", "description": "Build structural framework", "due_date": "2024-03-12 - 2024-04-01", "start_date": "2024-03-12", "end_date": "2024-04-01", "due_time": "07:00", "duration": "20 days", "priority": "high", "category": "personal"}, {"title": "Finishing Phase", "description": "Final finishing works", "due_date": "2024-04-02 - 2024-05-02", "start_date": "2024-04-02", "end_date": "2024-05-02", "due_time": "07:00", "duration": "30 days", "priority": "medium", "category": "personal"}]}},
                {"input": "Graduation project: research 3 weeks, writing 2 weeks, review 1 week", "output": {"tasks": [{"title": "Research Phase", "description": "Gather information and references", "due_date": "2024-04-01 - 2024-04-22", "start_date": "2024-04-01", "end_date": "2024-04-22", "due_time": "10:00", "duration": "21 days", "priority": "high", "category": "study"}, {"title": "Writing Phase", "description": "Write project content", "due_date": "2024-04-23 - 2024-05-07", "start_date": "2024-04-23", "end_date": "2024-05-07", "due_time": "10:00", "duration": "14 days", "priority": "high", "category": "study"}, {"title": "Review Phase", "description": "Review and correct errors", "due_date": "2024-05-08 - 2024-05-15", "start_date": "2024-05-08", "end_date": "2024-05-15", "due_time": "10:00", "duration": "7 days", "priority": "medium", "category": "study"}]}},
                {"input": "Wedding planning: venue booking 2 months prior, invitations 1 month prior, final arrangements 1 week", "output": {"tasks": [{"title": "Venue Booking", "description": "Book wedding and reception venue", "due_date": "2024-06-01", "due_time": "10:00", "duration": "1 day", "priority": "high", "category": "personal"}, {"title": "Send Invitations", "description": "Print and send wedding invitations", "due_date": "2024-07-01", "due_time": "10:00", "duration": "1 day", "priority": "medium", "category": "personal"}, {"title": "Final Arrangements", "description": "Confirm all details", "due_date": "2024-07-25 - 2024-08-01", "start_date": "2024-07-25", "end_date": "2024-08-01", "due_time": "10:00", "duration": "7 days", "priority": "high", "category": "personal"}]}},
                {"input": "Website development project: design 5 days, programming 10 days, deployment 2 days", "output": {"tasks": [{"title": "Website Design", "description": "Design user interfaces", "due_date": "2024-02-01 - 2024-02-06", "start_date": "2024-02-01", "end_date": "2024-02-06", "due_time": "09:00", "duration": "5 days", "priority": "high", "category": "work"}, {"title": "Website Programming", "description": "Develop features and functions", "due_date": "2024-02-07 - 2024-02-17", "start_date": "2024-02-07", "end_date": "2024-02-17", "due_time": "09:00", "duration": "10 days", "priority": "high", "category": "work"}, {"title": "Website Deployment", "description": "Upload website to server", "due_date": "2024-02-18 - 2024-02-20", "start_date": "2024-02-18", "end_date": "2024-02-20", "due_time": "09:00", "duration": "2 days", "priority": "medium", "category": "work"}]}},

                # Time-Specific Complex Tasks (25)
                {"input": "Team meeting every Monday and Wednesday at 11am for 1 hour", "output": {"tasks": [{"title": "Team Meeting", "description": "Weekly team coordination meeting", "due_date": "2024-01-15", "due_time": "11:00", "duration": "1 hour", "priority": "high", "category": "work"}, {"title": "Team Meeting", "description": "Weekly team coordination meeting", "due_date": "2024-01-17", "due_time": "11:00", "duration": "1 hour", "priority": "high", "category": "work"}]}},
                {"input": "English course every Tuesday and Thursday from 6 to 8pm", "output": {"tasks": [{"title": "English Course", "description": "Attend English language class", "due_date": "2024-01-16", "due_time": "18:00", "duration": "2 hours", "priority": "medium", "category": "study"}, {"title": "English Course", "description": "Attend English language class", "due_date": "2024-01-18", "due_time": "18:00", "duration": "2 hours", "priority": "medium", "category": "study"}]}},
                {"input": "Morning exercises daily from 7 to 7:45am", "output": {"tasks": [{"title": "Morning Exercises", "description": "Morning workout routine", "due_date": "2024-01-15", "due_time": "07:00", "duration": "45 minutes", "priority": "medium", "category": "health"}]}},
                {"input": "Quran reading after Fajr prayer for 30 minutes", "output": {"tasks": [{"title": "Quran Reading", "description": "Recite and memorize Quran", "due_date": "2024-01-15", "due_time": "05:30", "duration": "30 minutes", "priority": "high", "category": "personal"}]}},
                {"input": "Study subjects from 4 to 7pm daily except Friday", "output": {"tasks": [{"title": "Evening Study", "description": "Daily study session", "due_date": "2024-01-15", "due_time": "16:00", "duration": "3 hours", "priority": "high", "category": "study"}]}},

                # Advanced Task Combinations (25)
                {"input": "Create tasks for my vacation planning: book flights by Friday, hotel by next Monday, activities planning", "output": {"tasks": [{"title": "Book Flights", "description": "Research and book vacation flights", "due_date": "2024-01-19", "due_time": "14:00", "duration": "2 hours", "priority": "high", "category": "personal"}, {"title": "Book Hotel", "description": "Research and book accommodation", "due_date": "2024-01-22", "due_time": "14:00", "duration": "1 hour", "priority": "high", "category": "personal"}, {"title": "Plan Activities", "description": "Research and plan vacation activities", "due_date": "2024-01-24", "due_time": "16:00", "duration": "1.5 hours", "priority": "medium", "category": "personal"}]}},
                {"input": "Plan for birthday party: buy gifts, decorate place, prepare food, invite friends", "output": {"tasks": [{"title": "Buy Gifts", "description": "Purchase gifts for party", "due_date": "2024-03-20", "due_time": "15:00", "duration": "2 hours", "priority": "medium", "category": "personal"}, {"title": "Decorate Place", "description": "Arrange and decorate party venue", "due_date": "2024-03-24", "due_time": "10:00", "duration": "3 hours", "priority": "medium", "category": "personal"}, {"title": "Prepare Food", "description": "Prepare party meals", "due_date": "2024-03-24", "due_time": "14:00", "duration": "4 hours", "priority": "high", "category": "personal"}, {"title": "Invite Friends", "description": "Send attendance invitations", "due_date": "2024-03-18", "due_time": "12:00", "duration": "1 hour", "priority": "medium", "category": "personal"}]}},
                {"input": "Home renovation project: paint rooms, install flooring, renew furniture, final cleaning", "output": {"tasks": [{"title": "Paint Rooms", "description": "Paint house walls", "due_date": "2024-04-01 - 2024-04-03", "start_date": "2024-04-01", "end_date": "2024-04-03", "due_time": "08:00", "duration": "3 days", "priority": "high", "category": "personal"}, {"title": "Install Flooring", "description": "Install new flooring", "due_date": "2024-04-04 - 2024-04-06", "start_date": "2024-04-04", "end_date": "2024-04-06", "due_time": "08:00", "duration": "3 days", "priority": "high", "category": "personal"}, {"title": "Renew Furniture", "description": "Repair and renew furniture pieces", "due_date": "2024-04-07 - 2024-04-10", "start_date": "2024-04-07", "end_date": "2024-04-10", "due_time": "09:00", "duration": "4 days", "priority": "medium", "category": "personal"}, {"title": "Final Cleaning", "description": "Clean house after renovation", "due_date": "2024-04-11", "due_time": "08:00", "duration": "1 day", "priority": "medium", "category": "personal"}]}},
    ],
    
    'notes_ar': [
        # === ORIGINAL ARABIC NOTE EXAMPLES (50 examples) ===
                
                {"input": "ابحث عن الذكاء الاصطناعي", "output": {"notes": [{"title": "الذكاء الاصطناعي", "content": "الذكاء الاصطناعي هو مجال من مجالات علوم الكمبيوتر يهتم بإنشاء أنظمة قادرة على أداء مهام تتطلب ذكاءً بشرياً. يشمل التعلم الآلي، معالجة اللغة الطبيعية، الرؤية الحاسوبية، والروبوتات.", "category": "Research", "word_count": 45, "paragraph_count": 1}]}},
                {"input": "اكتب ملاحظة عن التغير المناخي", "output": {"notes": [{"title": "التغير المناخي", "content": "التغير المناخي يشير إلى التحولات طويلة الأجل في أنماط الطقس ودرجات الحرارة. الأسباب الرئيسية تشمل انبعاثات الغازات الدفيئة، إزالة الغابات، والأنشطة الصناعية. الآثار تشمل ارتفاع مستوى البحر، ظواهر جوية متطرفة، وتأثيرات على التنوع البيولوجي.", "category": "Research", "word_count": 55, "paragraph_count": 1}]}},
                {"input": "أنشئ ملاحظة لأفكار مشروعي", "output": {"notes": [{"title": "أفكار المشروع", "content": "1. تطبيق لإدارة المهام الذكية\n2. منصة للتعلم الإلكتروني\n3. نظام للزراعة الذكية\n4. تطبيق للصحة واللياقة\n5. منصة للعمل الحر", "category": "Ideas", "word_count": 30, "paragraph_count": 1}]}},
                {"input": "احفظ معلومات عن Python", "output": {"notes": [{"title": "لغة Python", "content": "بايثون هي لغة برمجة عالية المستوى، مفسرة، ذات أغراض عامة. تستخدم في تطوير الويب، تحليل البيانات، الذكاء الاصطناعي، والأتمتة. مزاياها: سهلة التعلم، مكتبات غنية، مجتمع نشط.", "category": "Reference", "word_count": 40, "paragraph_count": 1}]}},
                {"input": "اكتب ملاحظة شخصية", "output": {"notes": [{"title": "ملاحظة شخصية", "content": "أهدافي لهذا الأسبوع:\n- إنهاء المشروع\n- ممارسة الرياضة 3 مرات\n- قراءة 50 صفحة\n- تعلم مهارة جديدة", "category": "Personal", "word_count": 25, "paragraph_count": 1}]}},
                {"input": "ابحث عن الطاقة الشمسية", "output": {"notes": [{"title": "الطاقة الشمسية", "content": "الطاقة الشمسية هي الطاقة الناتجة عن الإشعاع الشمسي. يمكن تحويلها إلى طاقة كهربائية أو حرارية. من أهم تطبيقاتها: الألواح الشمسية، السخانات الشمسية، ومحطات الطاقة الشمسية.", "category": "Research", "word_count": 50, "paragraph_count": 1}]}},
                {"input": "اكتب عن التاريخ الإسلامي", "output": {"notes": [{"title": "التاريخ الإسلامي", "content": "يمتد التاريخ الإسلامي من بعثة النبي محمد صلى الله عليه وسلم إلى الوقت الحاضر. يشمل فترة الخلافة الراشدة، الدولة الأموية، الدولة العباسية، والدول الإسلامية المتعاقبة. تميزت بالازدهار العلمي والثقافي.", "category": "Research", "word_count": 60, "paragraph_count": 1}]}},
                {"input": "أنشئ ملاحظة للوصفات", "output": {"notes": [{"title": "الوصفات الشهية", "content": "وصفاتي المفضلة:\n1. الكسكس بالخضار\n2. الدجاج بالكركم\n3. سلطة التبولة\n4. حلوى القطايف\n5. شوربة العدس", "category": "Personal", "word_count": 25, "paragraph_count": 1}]}},
                {"input": "احفظ معلومات عن الرياضيات", "output": {"notes": [{"title": "مفاهيم رياضية", "content": "من أهم المفاهيم الرياضية:\n- الجبر: معادلات ومتغيرات\n- الهندسة: أشكال وقياسات\n- الإحصاء: تحليل البيانات\n- التفاضل والتكامل: معدلات التغير", "category": "Study", "word_count": 35, "paragraph_count": 1}]}},
                {"input": "اكتب عن الصحة النفسية", "output": {"notes": [{"title": "الصحة النفسية", "content": "الصحة النفسية تعني التوازن النفسي والعاطفي. تشمل القدرة على التعامل مع الضغوط، العمل المنتج، والإسهام في المجتمع. من طرق تحسينها: الرياضة، النوم الكافي، والتواصل الاجتماعي.", "category": "Research", "word_count": 55, "paragraph_count": 1}]}},

                # === ENHANCED ARABIC NOTE EXAMPLES (50 NEW examples) ===
                
                # Structured Notes with Word Counts (25)
                {"input": "اكتب ملاحظة بحثية عن الطاقة المتجددة بحوالي 500 كلمة", "output": {"notes": [{"title": "الطاقة المتجددة", "content": "الطاقة المتجددة هي الطاقة التي تأتي من مصادر طبيعية تتجدد باستمرار. تشمل:\n\n1. الطاقة الشمسية: تحويل ضوء الشمس إلى كهرباء\n2. طاقة الرياح: استخدام توربينات الرياح\n3. الطاقة الكهرومائية: من حركة المياه\n4. الطاقة الحيوية: من الكتلة الحيوية\n\nمزايا الطاقة المتجددة:\n- مستدامة ولا تنضب\n- صديقة للبيئة\n- تقلل الاعتماد على الوقود الأحفوري\n\nالتحديات:\n- التكلفة الأولية العالية\n- الاعتماد على الظروف الجوية\n- الحاجة لتقنيات تخزين متطورة", "category": "Research", "word_count": 180, "paragraph_count": 6}]}},
                {"input": "اكتب ملاحظة عن الذكاء الاصطناعي في 3 فقرات مع تفاصيل", "output": {"notes": [{"title": "تطبيقات الذكاء الاصطناعي", "content": "المقدمة\nالذكاء الاصطناعي يحول العالم من حولنا بسرعة كبيرة. من المساعدات الافتراضية إلى السيارات ذاتية القيادة، أصبحت هذه التقنية جزءاً أساسياً من حياتنا اليومية.\n\nالتطبيقات العملية\nفي مجال الرعاية الصحية، يساعد الذكاء الاصطناعي في تشخيص الأمراض وتحليل الصور الطبية. وفي التعليم، يوفر تعليماً مخصصاً لكل طالب بناءً على احتياجاته وقدراته.\n\nالمستقبل\nيتجه الذكاء الاصطناعي نحو أنظمة أكثر تطوراً قادرة على التفكير والإبداع. مع تقدم التعلم العميق والشبكات العصبية، سيكون له تأثير أكبر على جميع جوانب الحياة.", "category": "Research", "word_count": 150, "paragraph_count": 3}]}},
                {"input": "أنشئ ملاحظة عن برمجة Python مع أمثلة عملية", "output": {"notes": [{"title": "برمجة Python للمبتدئين", "content": "المقدمة\nبايثون لغة برمجة قوية وسهلة التعلم. تتميز ببساطة تركيبها مما يجعلها مثالية للمبتدئين.\n\nأمثلة عملية\nلطباعة جملة: print('Hello World')\nلحلقة تكرار: for i in range(5):\nلشرط: if x > 10:\n\nالمكتبات المهمة\n- NumPy للحسابات العلمية\n- Pandas لتحليل البيانات\n- Matplotlib للرسم البياني\n- TensorFlow للذكاء الاصطناعي", "category": "Study", "word_count": 120, "paragraph_count": 4}]}},
                {"input": "اكتب ملاحظة بحثية عن blockchain في 400 كلمة", "output": {"notes": [{"title": "تقنية Blockchain", "content": "المفهوم الأساسي\nBlockchain هي تقنية لتخزين المعلومات بطريقة لا يمكن تغييرها أو اختراقها. تعمل كسجل رقمي موزع يسجل المعاملات بشكل آمن.\n\nكيف تعمل\nتتكون من سلسلة من الكتل، كل كتلة تحتوي على مجموعة من المعاملات. عندما تكتمل الكتلة، تُضاف إلى السلسلة بشكل دائم.\n\nالتطبيقات\n- العملات الرقمية مثل Bitcoin\n- العقود الذكية\n- سلسلة التوريد\n- أنظمة التصويت\n\nالمزايا\n- الشفافية\n- الأمان\n- اللامركزية\n- عدم القدرة على التزوير", "category": "Research", "word_count": 140, "paragraph_count": 5}]}},
                {"input": "أنشئ ملاحظة عن إدارة الوقت بخطوات عملية", "output": {"notes": [{"title": "فن إدارة الوقت", "content": "المقدمة\nإدارة الوقت مهارة أساسية للنجاح في الحياة الشخصية والمهنية. تساعد في تحقيق الأهداف وتقليل التوتر.\n\nالخطوات العملية\n1. تحديد الأولويات: استخدام مصفوفة أيزنهاور\n2. التخطيط اليومي: كتابة المهام صباحاً\n3. تقنية بومودورو: العمل 25 دقيقة ثم راحة 5\n4. تجديد multitasking: التركيز على مهمة واحدة\n5. المراجعة المسائية: تقييم الإنجازات\n\nنصائح إضافية\n- تعلم قول لا للمهام غير المهمة\n- تفويض المهام عندما يكون ذلك ممكناً\n- أخذ فترات راحة منتظمة\n- استخدام الأدوات الرقمية للمساعدة", "category": "Personal", "word_count": 160, "paragraph_count": 4}]}},

                # Complex Research Notes (25)
                {"input": "ابحث عن تاريخ الحضارة الإسلامية في 3 فقرات مع عناوين فرعية", "output": {"notes": [{"title": "تاريخ الحضارة الإسلامية", "content": "العصر الذهبي للإسلام\nشهدت الفترة من القرن الثامن إلى القرن الرابع عشر ازدهاراً كبيراً في العلوم والثقافة في العالم الإسلامي. قدم العلماء المسلمون إسهامات كبيرة في الرياضيات والطب والفلك.\n\nالإنجازات العلمية\nمن أهم الإسهامات: تطوير الجبر، تقديم نظام الترقيم، تقدم كبير في الطب مع كتب مثل القانون في الطب لابن سينا، وتطوير المراصد الفلكية.\n\nالتأثير الثقافي\nانتشرت الحضارة الإسلامية من الأندلس في الغرب إلى الهند في الشرق، مؤثرة على الثقافات المحلية وناقلة المعرفة بين الحضارات.", "category": "Research", "word_count": 150, "paragraph_count": 3}]}},
                {"input": "اكتب عن الثورة الصناعية الرابعة وتأثيرها", "output": {"notes": [{"title": "الثورة الصناعية الرابعة", "content": "المفهوم\nتشير الثورة الصناعية الرابعة إلى الدمج بين التقنيات المادية والرقمية والبيولوجية. تختلف عن سابقاتها بسرعة تطورها وتأثيرها الشامل.\n\nالتقنيات الأساسية\n- الذكاء الاصطناعي والتعلم الآلي\n- إنترنت الأشياء\n- الطباعة ثلاثية الأبعاد\n- التقنية الحيوية\n- المركبات ذاتية القيادة\n\nالتأثير على سوق العمل\nستختفي بعض الوظائف التقليدية وتظهر وظائف جديدة. سيزداد الطلب على المهارات الرقمية والتحليلية والإبداعية.", "category": "Research", "word_count": 130, "paragraph_count": 3}]}},
                {"input": "ابحث عن علم البيانات وتحليلها", "output": {"notes": [{"title": "علم البيانات وتحليله", "content": "المقدمة\nعلم البيانات مجال متعدد التخصصات يجمع بين الإحصاء، البرمجة، والمعرفة المجالية لاستخلاص insights من البيانات.\n\nمراحل تحليل البيانات\n1. جمع البيانات: من مصادر مختلفة\n2. تنظيف البيانات: معالجة القيم المفقودة\n3. التحليل الاستكشافي: فهم طبيعة البيانات\n4. النمذجة: بناء نماذج تنبؤية\n5. التصور: عرض النتائج بيانياً\n\nالأدوات المستخدمة\n- Python مع مكتبات Pandas, NumPy\n- R للإحصاء\n- SQL لقواعد البيانات\n- Tableau للتصور", "category": "Study", "word_count": 140, "paragraph_count": 4}]}},

                # Personal and Project Notes (25)
                {"input": "أنشئ ملاحظة شخصية لأهدافي السنوية مع تفاصيل ومؤشرات قياس", "output": {"notes": [{"title": "الأهداف السنوية", "content": "الأهداف الشخصية والمهنية لهذا العام:\n\nالتطوير المهني:\n- إكمال 3 دورات تدريبية\n- تعلم لغة برمجة جديدة\n- المشاركة في مؤتمرين\n\nالصحة واللياقة:\n- ممارسة الرياضة 4 مرات أسبوعياً\n- خسارة 5 كيلو جرام\n- النوم 7 ساعات يومياً\n\nالتطور الشخصي:\n- قراءة 12 كتاباً\n- تعلم مهارة جديدة\n- السفر إلى 3 دول جديدة\n\nالمؤشرات:\n- متابعة التقدم شهرياً\n- تعديل الخطط عند الحاجة\n- الاحتفال بالإنجازات", "category": "Personal", "word_count": 120, "paragraph_count": 5}]}},
                {"input": "اكتب خطة مشروع تطوير تطبيق جوال", "output": {"notes": [{"title": "خطة تطوير تطبيق جوال", "content": "مراحل المشروع:\n\n1. التحليل والتصميم (أسبوعان)\n- دراسة متطلبات المستخدم\n- تصميم واجهات المستخدم\n- وضع خطة المشروع\n\n2. التطوير (4 أسابيع)\n- تطوير الواجهة الأمامية\n- برمجة الخلفية\n- تكامل واجهة برمجة التطبيقات\n\n3. الاختبار (أسبوع)\n- اختبار الوظائف\n- اختبار الأداء\n- اختبار الأمان\n\n4. النشر (3 أيام)\n- رفع التطبيق للمتاجر\n- التسويق المبدئي\n- جمع التغذية الراجعة", "category": "Work", "word_count": 110, "paragraph_count": 5}]}},
                {"input": "أنشئ ملاحظة لتخطيط رحلة سياحية", "output": {"notes": [{"title": "تخطيط الرحلة السياحية", "content": "تفاصيل الرحلة:\n\nالوجهة: تركيا\nالمدة: 10 أيام\nالميزانية: 5000 دولار\n\nالتحضيرات:\n- حجز تذاكر الطيران\n- تأمين فنادق\n- تجهيز التأشيرة\n- صرف العملة\n\nالأنشطة المخطط لها:\n- زيارة آيا صوفيا والمسجد الأزرق\n- جولة في الأسواق التقليدية\n- رحلة بالمنطاد في كابادوكيا\n- زيارة شواطئ أنطاليا\n\nقائمة المستلزمات:\n- ملابس مناسبة للمناخ\n- أدوية شخصية\n- كاميرا وملحقاتها\n- مستندات السفر", "category": "Personal", "word_count": 130, "paragraph_count": 5}]}},
        
    ],
    
    'notes_en': [
        # === ORIGINAL ENGLISH NOTE EXAMPLES (50 examples) ===
                
                {"input": "Research artificial intelligence", "output": {"notes": [{"title": "Artificial Intelligence", "content": "Artificial Intelligence is a field of computer science focused on creating systems capable of performing tasks that typically require human intelligence. It includes machine learning, natural language processing, computer vision, and robotics.", "category": "Research", "word_count": 40, "paragraph_count": 1}]}},
                {"input": "Write note about climate change", "output": {"notes": [{"title": "Climate Change", "content": "Climate change refers to long-term shifts in weather patterns and temperatures. Main causes include greenhouse gas emissions, deforestation, and industrial activities. Effects include sea level rise, extreme weather events, and impacts on biodiversity.", "category": "Research", "word_count": 45, "paragraph_count": 1}]}},
                {"input": "Create note for my project ideas", "output": {"notes": [{"title": "Project Ideas", "content": "1. Smart task management app\n2. E-learning platform\n3. Smart agriculture system\n4. Health and fitness app\n5. Freelance work platform", "category": "Ideas", "word_count": 25, "paragraph_count": 1}]}},
                {"input": "Save information about Python", "output": {"notes": [{"title": "Python Language", "content": "Python is a high-level, interpreted, general-purpose programming language. Used in web development, data analysis, artificial intelligence, and automation. Advantages: easy to learn, rich libraries, active community.", "category": "Reference", "word_count": 35, "paragraph_count": 1}]}},
                {"input": "Write personal note", "output": {"notes": [{"title": "Personal Note", "content": "My goals for this week:\n- Finish the project\n- Exercise 3 times\n- Read 50 pages\n- Learn a new skill", "category": "Personal", "word_count": 20, "paragraph_count": 1}]}},
                {"input": "Research solar energy", "output": {"notes": [{"title": "Solar Energy", "content": "Solar energy is energy from the sun's radiation. It can be converted into electrical or thermal energy. Key applications include: solar panels, solar water heaters, and solar power plants.", "category": "Research", "word_count": 40, "paragraph_count": 1}]}},
                {"input": "Write about Islamic history", "output": {"notes": [{"title": "Islamic History", "content": "Islamic history spans from the prophethood of Muhammad (PBUH) to the present day. It includes the Rashidun Caliphate, Umayyad Dynasty, Abbasid Dynasty, and successive Islamic states. Characterized by scientific and cultural flourishing.", "category": "Research", "word_count": 50, "paragraph_count": 1}]}},
                {"input": "Create note for recipes", "output": {"notes": [{"title": "Delicious Recipes", "content": "My favorite recipes:\n1. Couscous with vegetables\n2. Turmeric chicken\n3. Tabbouleh salad\n4. Qatayef dessert\n5. Lentil soup", "category": "Personal", "word_count": 20, "paragraph_count": 1}]}},
                {"input": "Save information about mathematics", "output": {"notes": [{"title": "Mathematical Concepts", "content": "Key mathematical concepts:\n- Algebra: equations and variables\n- Geometry: shapes and measurements\n- Statistics: data analysis\n- Calculus: rates of change", "category": "Study", "word_count": 25, "paragraph_count": 1}]}},
                {"input": "Write about mental health", "output": {"notes": [{"title": "Mental Health", "content": "Mental health means psychological and emotional balance. Includes ability to handle stress, productive work, and contributing to society. Improvement methods: exercise, adequate sleep, and social connection.", "category": "Research", "word_count": 45, "paragraph_count": 1}]}},

                # === ENHANCED ENGLISH NOTE EXAMPLES (50 NEW examples) ===
                
                # Structured Notes with Word Counts (25)
                {"input": "Write a research note about renewable energy with approximately 500 words", "output": {"notes": [{"title": "Renewable Energy", "content": "Renewable energy comes from natural sources that are constantly replenished. Major types include:\n\n1. Solar Energy: Converting sunlight into electricity\n2. Wind Energy: Using wind turbines\n3. Hydropower: From moving water\n4. Biomass Energy: From organic materials\n\nAdvantages of Renewable Energy:\n- Sustainable and inexhaustible\n- Environmentally friendly\n- Reduces dependence on fossil fuels\n\nChallenges:\n- High initial costs\n- Weather dependency\n- Need for advanced storage technologies\n\nFuture Outlook:\nContinuous technological advancements are making renewable energy more efficient and affordable, positioning it as the future of global energy supply.", "category": "Research", "word_count": 150, "paragraph_count": 6}]}},
                {"input": "Write note about artificial intelligence in 3 paragraphs with details", "output": {"notes": [{"title": "AI Applications", "content": "Introduction\nArtificial intelligence is transforming our world at an incredible pace. From virtual assistants to self-driving cars, this technology has become an essential part of our daily lives.\n\nPractical Applications\nIn healthcare, AI helps diagnose diseases and analyze medical images. In education, it provides personalized learning for each student based on their needs and abilities.\n\nThe Future\nAI is moving toward more advanced systems capable of thinking and creativity. With advances in deep learning and neural networks, it will have greater impact on all aspects of life.", "category": "Research", "word_count": 120, "paragraph_count": 3}]}},
                {"input": "Create note about Python programming with practical examples", "output": {"notes": [{"title": "Python Programming for Beginners", "content": "Introduction\nPython is a powerful and easy-to-learn programming language. It features simple syntax that makes it ideal for beginners.\n\nPractical Examples\nTo print a sentence: print('Hello World')\nFor a loop: for i in range(5):\nFor a condition: if x > 10:\n\nImportant Libraries\n- NumPy for scientific computing\n- Pandas for data analysis\n- Matplotlib for plotting\n- TensorFlow for artificial intelligence", "category": "Study", "word_count": 100, "paragraph_count": 4}]}},
                {"input": "Write research note about blockchain in 400 words", "output": {"notes": [{"title": "Blockchain Technology", "content": "Basic Concept\nBlockchain is a technology for storing information in a way that cannot be changed or hacked. It works as a distributed digital ledger that records transactions securely.\n\nHow It Works\nIt consists of a chain of blocks, each containing a set of transactions. When a block is completed, it's added to the chain permanently.\n\nApplications\n- Digital currencies like Bitcoin\n- Smart contracts\n- Supply chain\n- Voting systems\n\nAdvantages\n- Transparency\n- Security\n- Decentralization\n- Inability to counterfeit", "category": "Research", "word_count": 120, "paragraph_count": 5}]}},
                {"input": "Create note about time management with practical steps", "output": {"notes": [{"title": "The Art of Time Management", "content": "Introduction\nTime management is an essential skill for success in personal and professional life. It helps achieve goals and reduce stress.\n\nPractical Steps\n1. Set priorities: Use Eisenhower Matrix\n2. Daily planning: Write tasks in the morning\n3. Pomodoro technique: Work 25 minutes then break 5\n4. Avoid multitasking: Focus on one task\n5. Evening review: Evaluate achievements\n\nAdditional Tips\n- Learn to say no to unimportant tasks\n- Delegate tasks when possible\n- Take regular breaks\n- Use digital tools for assistance", "category": "Personal", "word_count": 130, "paragraph_count": 4}]}},

                # Complex Research Notes (25)
                {"input": "Research about ancient civilizations in 3 paragraphs with subheadings", "output": {"notes": [{"title": "Ancient Civilizations", "content": "Mesopotamian Civilization\nLocated between the Tigris and Euphrates rivers, Mesopotamia was one of the earliest civilizations. They developed writing (cuneiform), established legal codes like Hammurabi's Code, and made significant advances in mathematics and astronomy.\n\nAncient Egypt\nKnown for its pyramids, hieroglyphic writing, and advanced understanding of engineering and medicine. Egyptian society was highly structured with pharaohs at the top, and they made remarkable contributions to architecture and timekeeping.\n\nAncient Greece\nThe Greeks pioneered democracy, philosophy, and scientific thinking. With figures like Socrates, Plato, and Aristotle, they laid foundations for Western thought while making advances in mathematics, medicine, and the arts that influence us today.", "category": "Research", "word_count": 160, "paragraph_count": 3}]}},
                {"input": "Write about the Fourth Industrial Revolution and its impact", "output": {"notes": [{"title": "Fourth Industrial Revolution", "content": "Concept\nThe Fourth Industrial Revolution refers to the fusion of physical, digital, and biological technologies. It differs from its predecessors in its speed of development and comprehensive impact.\n\nCore Technologies\n- Artificial intelligence and machine learning\n- Internet of Things\n- 3D printing\n- Biotechnology\n- Self-driving vehicles\n\nImpact on Job Market\nSome traditional jobs will disappear and new ones will emerge. Demand for digital, analytical, and creative skills will increase.", "category": "Research", "word_count": 110, "paragraph_count": 3}]}},
                {"input": "Research data science and its analysis", "output": {"notes": [{"title": "Data Science and Analysis", "content": "Introduction\nData science is an interdisciplinary field combining statistics, programming, and domain knowledge to extract insights from data.\n\nData Analysis Stages\n1. Data collection: From various sources\n2. Data cleaning: Handling missing values\n3. Exploratory analysis: Understanding data nature\n4. Modeling: Building predictive models\n5. Visualization: Displaying results graphically\n\nTools Used\n- Python with Pandas, NumPy libraries\n- R for statistics\n- SQL for databases\n- Tableau for visualization", "category": "Study", "word_count": 120, "paragraph_count": 4}]}},

                # Personal and Project Notes (25)
                {"input": "Create a personal note for my annual goals with detailed milestones and metrics", "output": {"notes": [{"title": "Annual Goals and Objectives", "content": "Personal and Professional Development Goals:\n\nCareer Development:\n- Complete 3 professional certifications\n- Learn a new programming language\n- Attend 2 industry conferences\n- Lead one major project\n\nHealth and Fitness:\n- Exercise 4 times per week\n- Lose 10 pounds\n- Sleep 7 hours nightly\n- Meditate daily\n\nPersonal Growth:\n- Read 12 books\n- Learn a new skill (photography)\n- Travel to 3 new countries\n- Volunteer 50 hours\n\nFinancial Goals:\n- Save 20% of income\n- Invest in retirement account\n- Pay off credit card debt\n\nMetrics:\n- Monthly progress tracking\n- Plan adjustments when needed\n- Celebrating achievements", "category": "Personal", "word_count": 140, "paragraph_count": 5}]}},
                {"input": "Write project plan for mobile app development", "output": {"notes": [{"title": "Mobile App Development Plan", "content": "Project Phases:\n\n1. Analysis & Design (2 weeks)\n- Study user requirements\n- Design user interfaces\n- Create project plan\n\n2. Development (4 weeks)\n- Develop frontend\n- Program backend\n- API integration\n\n3. Testing (1 week)\n- Functionality testing\n- Performance testing\n- Security testing\n\n4. Deployment (3 days)\n- Upload to app stores\n- Initial marketing\n- Collect feedback", "category": "Work", "word_count": 90, "paragraph_count": 5}]}},
                {"input": "Create note for travel planning", "output": {"notes": [{"title": "Travel Planning", "content": "Trip Details:\n\nDestination: Turkey\nDuration: 10 days\nBudget: $5000\n\nPreparations:\n- Book flight tickets\n- Secure hotels\n- Prepare visa\n- Exchange currency\n\nPlanned Activities:\n- Visit Hagia Sophia and Blue Mosque\n- Tour traditional markets\n- Hot air balloon ride in Cappadocia\n- Visit Antalya beaches\n\nPacking List:\n- Weather-appropriate clothing\n- Personal medications\n- Camera and accessories\n- Travel documents", "category": "Personal", "word_count": 110, "paragraph_count": 5}]}},

                # Technical and Study Notes (25)
                {"input": "Create study notes for machine learning concepts with examples and formulas", "output": {"notes": [{"title": "Machine Learning Fundamentals", "content": "Core Concepts:\n\nSupervised Learning:\n- Training with labeled data\n- Examples: Classification, Regression\n- Key algorithms: Linear Regression, SVM, Neural Networks\n\nUnsupervised Learning:\n- Finding patterns in unlabeled data\n- Examples: Clustering, Dimensionality Reduction\n- Key algorithms: K-means, PCA\n\nImportant Formulas:\n- Linear Regression: y = mx + b\n- Sigmoid Function: σ(x) = 1 / (1 + e^(-x))\n- Cost Function: J(θ) = (1/2m) Σ(hθ(x) - y)^2\n\nEvaluation Metrics:\n- Accuracy, Precision, Recall\n- F1 Score, ROC Curve\n- Confusion Matrix Analysis", "category": "Study", "word_count": 130, "paragraph_count": 6}]}},
        
    ]
}